In [4]:
import random
import numpy as np

In [25]:
def create_grid(square_len, delta):
    A = []
    cell_no = int(square_len / delta)
    random.seed(23)
    A = np.ndarray(shape=(cell_no, cell_no), dtype=float)
    for i in range(cell_no):
        for j in range(cell_no):
            val = random.random() * square_len / 2
            A.itemset((i, j), val)
    return A

In [40]:
A = create_grid(1, 0.01)

In [82]:
A = create_grid(1, 0.01)
B = A.flatten()
B

array([0.46243263, 0.47430289, 0.44621667, ..., 0.08781881, 0.34166736,
       0.47286528])

In [42]:
def split_grid(A, proc_no):
    if A.shape[0] % proc_no != 0:
        raise RuntimeError
    result = np.split(A, proc_no)
    return result

In [75]:
res = split_grid(A, 10)
res[0].shape

(10, 100)

In [46]:
proc_zero_array = res[0]

In [54]:
proc_zero_array[9][99]

0.1664396789274133

In [59]:
A[0][101]

IndexError: index 101 is out of bounds for axis 0 with size 100

In [66]:
a = 10000000
a in range(A.shape[0])

False

In [67]:
tmp = np.empty([10,100], dtype='i')

In [69]:
tmp.shape

(10, 100)

In [70]:
tmp.T[:,:] = range(10)

In [71]:
tmp

array([[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
        1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
        1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
        1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
        1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
        2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
        2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
        2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
        2, 2, 2, 2, 2,

In [83]:
a = [[1,2],[2,3]]

In [96]:
b = np.array(a)
b

array([[1, 2],
       [2, 3]])

In [92]:
c = b.flatten()

In [95]:
np.array(c).reshape(2,2)

array([[1, 2],
       [2, 3]])

In [97]:
np.full(10, 10)

array([10, 10, 10, 10, 10, 10, 10, 10, 10, 10])

In [99]:
b

array([[1, 2],
       [2, 3]])

In [104]:
c = np.append([0, 0], b.flatten())
c = np.append(c, [0, 0])
c

array([0, 0, 1, 2, 2, 3, 0, 0])

In [107]:
np.zeros(2, dtype=np.float64)

array([0., 0.])

In [111]:
c

array([0, 0, 1, 2, 2, 3, 0, 0])

In [113]:
vector_len = 8
d = np.split(c, [2,vector_len-2])
d

[array([0, 0]), array([1, 2, 2, 3]), array([0, 0])]

In [114]:
flat_array = d[1]
flat_array

array([1, 2, 2, 3])

In [116]:
width = 2
height = 2
grid = flat_array.reshape((4, 1))
grid

array([[1],
       [2],
       [2],
       [3]])

In [122]:
x = np.split(flat_array, [2,3])
flat

[array([1, 2]), array([2]), array([3])]

In [128]:
first_row, center, last_row = np.split(flat_array, [2, flat_array.size-1])
last_row

array([3])

In [5]:
a = np.zeros((2,3))

In [7]:
def create_grid(square_len, delta):
    cell_no = int(square_len / delta)
    random.seed(23)
    A = np.ndarray(shape=(cell_no, cell_no), dtype=float)
    for i in range(cell_no):
        for j in range(cell_no):
            val = random.random() * square_len / 2
            A.itemset((i, j), val)
    return A

In [9]:
cell_no = 10
height = 10
processors=5
vector_len = 2*height+2*height
A = create_grid(1, np.float64(1.0/np.float64(cell_no)))
A_flat = A.flatten()
# Add upper and lower arrays
send_data = np.append(np.zeros(height, dtype=np.float64), A_flat)
send_data = np.append(send_data, np.zeros(height, dtype=np.float64))

# counts = np.full(processors, vector_len)
# due to old version of numpy
counts = np.ones(processors)*vector_len
displacements = [i*(vector_len - 2*height) for i in range(processors)]

In [13]:
displacements


[0, 20, 40, 60, 80]

In [38]:
import numpy as np
X = list(range(-10, 10))
Y = list(range(-10, 10))

In [39]:
X, Y = np.meshgrid(X, Y)
d = []
for x in X:
    for y in Y:
        d.append(np.sqrt(x**2 + y**2))
d

[array([14.14213562, 13.45362405, 12.80624847, 12.20655562, 11.66190379,
        11.18033989, 10.77032961, 10.44030651, 10.19803903, 10.04987562,
        10.        , 10.04987562, 10.19803903, 10.44030651, 10.77032961,
        11.18033989, 11.66190379, 12.20655562, 12.80624847, 13.45362405]),
 array([13.45362405, 12.72792206, 12.04159458, 11.40175425, 10.81665383,
        10.29563014,  9.8488578 ,  9.48683298,  9.21954446,  9.05538514,
         9.        ,  9.05538514,  9.21954446,  9.48683298,  9.8488578 ,
        10.29563014, 10.81665383, 11.40175425, 12.04159458, 12.72792206]),
 array([12.80624847, 12.04159458, 11.3137085 , 10.63014581, 10.        ,
         9.43398113,  8.94427191,  8.54400375,  8.24621125,  8.06225775,
         8.        ,  8.06225775,  8.24621125,  8.54400375,  8.94427191,
         9.43398113, 10.        , 10.63014581, 11.3137085 , 12.04159458]),
 array([12.20655562, 11.40175425, 10.63014581,  9.89949494,  9.21954446,
         8.60232527,  8.06225775,  7.61577311

In [45]:
Z = np.random.rand(20,20)
Z

array([[3.20702699e-01, 8.00076990e-01, 9.23885352e-01, 9.32323126e-01,
        9.81804718e-01, 6.67886941e-01, 9.52818060e-01, 2.62126258e-01,
        5.81707716e-01, 8.06810659e-01, 9.94115647e-01, 9.98757346e-01,
        3.84859399e-01, 4.83672760e-01, 2.04115032e-01, 9.95306242e-01,
        7.14320232e-01, 6.49436910e-02, 8.89409335e-01, 6.76942334e-02],
       [3.42894163e-01, 9.45792573e-01, 9.10887509e-01, 2.46273207e-01,
        4.70582921e-01, 7.31730489e-01, 4.19700907e-02, 2.08328180e-02,
        4.76833967e-01, 4.83348584e-01, 5.01654147e-01, 3.71661351e-01,
        2.77543152e-01, 2.90788494e-01, 6.80164777e-01, 6.28931744e-01,
        2.38524922e-01, 3.47278840e-01, 3.31974767e-01, 3.72734202e-01],
       [1.79695925e-01, 6.41151440e-02, 3.90195754e-01, 2.88193267e-01,
        2.60866761e-01, 6.30907417e-01, 8.27117540e-01, 4.59102415e-01,
        5.93314140e-01, 5.17489049e-01, 7.33600100e-01, 6.36551352e-01,
        9.87531196e-01, 1.26844413e-01, 6.89177896e-01, 9.2140

In [11]:
X, Y = np.meshgrid(X, Y)

In [47]:
c = np.sqrt(X**2 + Y**2)
np.save("numpy_lol", c)

In [48]:
c_new = np.load('numpy_lol.npy')
c_new

array([[14.14213562, 13.45362405, 12.80624847, 12.20655562, 11.66190379,
        11.18033989, 10.77032961, 10.44030651, 10.19803903, 10.04987562,
        10.        , 10.04987562, 10.19803903, 10.44030651, 10.77032961,
        11.18033989, 11.66190379, 12.20655562, 12.80624847, 13.45362405],
       [13.45362405, 12.72792206, 12.04159458, 11.40175425, 10.81665383,
        10.29563014,  9.8488578 ,  9.48683298,  9.21954446,  9.05538514,
         9.        ,  9.05538514,  9.21954446,  9.48683298,  9.8488578 ,
        10.29563014, 10.81665383, 11.40175425, 12.04159458, 12.72792206],
       [12.80624847, 12.04159458, 11.3137085 , 10.63014581, 10.        ,
         9.43398113,  8.94427191,  8.54400375,  8.24621125,  8.06225775,
         8.        ,  8.06225775,  8.24621125,  8.54400375,  8.94427191,
         9.43398113, 10.        , 10.63014581, 11.3137085 , 12.04159458],
       [12.20655562, 11.40175425, 10.63014581,  9.89949494,  9.21954446,
         8.60232527,  8.06225775,  7.61577311,  

In [20]:
from mpl_toolkits.mplot3d import Axes3D
import matplotlib.pyplot as plt
from matplotlib import cm
from matplotlib.ticker import LinearLocator, FormatStrFormatter
from matplotlib.pyplot import savefig

In [61]:
def save_fig(path, X, Y, Z):
    fig = plt.figure()
    ax = fig.gca(projection='3d')
    # Plot the surface.
    surf = ax.plot_surface(X, Y, Z, cmap=cm.coolwarm,
                           linewidth=0, antialiased=False)

    # Customize the z axis.
    ax.set_zlim(-1.01, 1.01)
    ax.zaxis.set_major_locator(LinearLocator(10))
    ax.zaxis.set_major_formatter(FormatStrFormatter('%.02f'))

    # Add a color bar which maps values to colors.
    fig.colorbar(surf, shrink=0.5, aspect=5)

    savefig(path)

In [ ]:
X = list(range(120))
Y = list(range(120))
X, Y = np.meshgrid(X, Y)
for i in range(100):
    Z = np.load("./figures/grid_{}.npy".format(i))
    save_fig("./images/img_{}.png".format(i), X, Y, Z)

D:\Anaconda\Anaconda\lib\site-packages\matplotlib\pyplot.py:528: RuntimeWarning: More than 20 figures have been opened. Figures created through the pyplot interface (`matplotlib.pyplot.figure`) are retained until explicitly closed and may consume too much memory. (To control this warning, see the rcParam `figure.max_open_warning`).
  max_open_warning, RuntimeWarning)
